server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
management:
  security:
    enabled: false
spring:
  datasource:
    password: abelkelly
    url: jdbc:postgresql://localhost:5432/fraud
    username: root
  application:
    name: notification
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true